### ISSUE TITLE
How can I get this?

### ISSUE THREAD

**Issue by YoungPup** [PrinceFroggy/sBot#10]
How can I get this? And can it add multiple items to the same cart?

**Comment by PrinceFroggy** [comment]
csBot is the newest uncompleted version of sBot.

You have to code the rest for it to work as I am IP banned from Supreme.

**Comment by YoungPup** [comment]
How'd you get IP banned?

**Comment by PrinceFroggy** [comment]
They found out I made a bot, instantly IP banned me via my full name.

**Comment by YoungPup** [comment]
What exactly needs to be coded?

**Comment by PrinceFroggy** [comment]
sBot worked for 2 years straight bypassing patches Supreme made for it not to work.
Recently they blocked the use of the .net control webBrowser so I made csBot using a differen't webBrowser known as CEFSharp.

In the Supreme.cs, you can see in the csBot that I just wrote code up to selecting the size, nothing else (skeleton remains from sBot of the structure of how the code should go)...that is what is left to write, which isn't much.
