### ISSUE TITLE
Working still?

### ISSUE THREAD

**Issue by limsammy** [PrinceFroggy/sBot#11]
Have you or anyone tested this with the latest 2017 drop?

**Comment by PrinceFroggy** [comment]
sBot worked for 2 years and no longer works as Supreme blocked the webBrowser.

sBot has the working ID's for the bot as that never changes.

csBot uses a new webBrowser and bypasses the Supreme block; however, I only coded it up until selecting the size of the item as I then got IP banned from Supreme.

I suggest finding another bot unless you are able to code the rest which is not hard.
