### ISSUE TITLE
can you help me learn about this sort of stuff?

### ISSUE THREAD

**Issue by mileseva** [PrinceFroggy/sBot#12]
thank you, and if you can't no worries

**Comment by PrinceFroggy** [comment]
what do you want to learn?

**Comment by PrinceFroggy** [comment]
depending on what you want to learn, there are many websites via google that teach programming languages.

Currently I am physically in a iOS bootcamp in Toronto,Canada and it ends May 4th.

After that I will be purchasing a course here to learn x86 assembly: https://www.udemy.com/x86-asm-foundations/

Other courses can be learn't here: https://teamtreehouse.com/tracks

**Comment by mileseva** [comment]
just want to learn how to install and run various bots using C# and python, thanks.

**Comment by randylicata** [comment]
I suggest starting with a high level language like Python. Code Academy is a great resource to help you get started. When I first worked with Python I used the _Wing IDE_. Programming is hard to grasp at first (at least for me it was) but with practice and over time I think anyone can become a great programmer. Don't jump into complex projects like a Supreme bot at first - learn the concepts and a language first. The most important thing to note though: Don't get discouraged if you don't get it at first. Let me know if you need help!
