### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by samhardwick01** [PrinceFroggy/sBot#2]
what do you do after youve put your details and item details in?

**Comment by PrinceFroggy** [comment]
UPDATING AS THEY ENCRYPTED!

**Comment by PrinceFroggy** [comment]
STILL WORKS AS OF THURSDAY NOVEMBER 24, 2016.

YOU CLICK ITEM.

**Comment by samhardwick01** [comment]
so on the supreme website you click the item?

**Comment by PrinceFroggy** [comment]
no in the bot you click the item, click insert to see items generated!

**Comment by jonathandion** [comment]
@PrinceFroggy How do we choose the size ? There is no dropdown at all.

**Comment by PrinceFroggy** [comment]
https://www.youtube.com/watch?v=tv7Q7u_CF0A

THIS IS USED FOR PROGRAMMERS; YOU NEED TO BUILD AND RUN THIS ON YOUR OWN!
