### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by bvvst** [PrinceFroggy/sBot#4]
Does the bot have a built in VPN?

I'm a little bit confused as to how some of the info is formatted, could you show me exactly how to format the phone number and cvv number?

What did you do to start the bot after all the info is entered?

Thanks <3

**Comment by PrinceFroggy** [comment]
Check the README for a youtube link to see how to set up.

YOU NEED VISUAL STUDIO WINDOWS 7 TO RUN THIS TO WORK 100%, DEBUG OR BUILD AND RUN.

YOU CANNOT JUST DOWNLOAD BOT ELSE IT WILL NOT WORK DUE TO FRAMEWORK ISSUES.

no vpn.
