### ISSUE TITLE
FIXING BOT SO YOU DO NOT HAVE TO USE VISUAL STUDIO!

### ISSUE THREAD

**Issue by PrinceFroggy** [PrinceFroggy/sBot#5]
GIVE ME 2 DAYS!

**Comment by PrinceFroggy** [comment]
@vhad500
@jedinak95
@Gudui
@samkennedy0
@samhardwick01
@jonathandion
@paralapazoid
@lukeimbing

**Comment by PrinceFroggy** [comment]
CHECK THE READ ME FOR LATEST INFORMATION!

**Comment by randylicata** [comment]
@PrinceFroggy What was the issue with not running it in VS? Ran it as a standalone .exe and it ran (not sure if it worked)

**Comment by PrinceFroggy** [comment]
The issue when running as the standalone.exe was that it would not call out a function in the process of automation maybe due to the HTMLAGILITYPACK.dll not being present?

I was going to fix this issue but I discovered that SUPREME decided to block the native .NET WEBBROWSER control from the /checkout link (debugged and when I navigate to checkout the page will not load); therefore, I am going to fix this issue first than the standalone .exe issue (worked then 100% if you run via VISUAL STUDIO).

So as of this moment, the functions in the program work 100% (automation of to selection, checkout and paying) but the method of using the native .net control is BLOCKED as far as I know (when navigating to checkout link it does not load).

Thanks for your patience.

After reviewing what is the problem, it has been determined 100% that upon navigating to checkout link, if you are using a .net WEBBROWSER control you will be BLOCKED.

I may or may not fix this as I never really intended to carry this project this far out into development (originally bypassed encryption name, etc).

Thanks.

**Comment by randylicata** [comment]
@PrinceFroggy Interesting. I have very limited knowledge about web dev as I'm more on the embedded control side of things. Much love to you trying to fix this

**Comment by PrinceFroggy** [comment]
I will be testing a possible solution using the .net framework of 4.2.5 and using a chrome based web browser. If it is still blocked, there is a possible solution but it is a web-browser extension that costs $. The project currently works fine just that the checkout is blocked via using the .net control.

**Comment by PrinceFroggy** [comment]
Using CefSharp I was able to navigate to checkout; therefore, if there is a will, there is a way!

**Comment by PrinceFroggy** [comment]
READ THE README.
