### ISSUE TITLE
sBot will cost $$

### ISSUE THREAD

**Issue by PrinceFroggy** [PrinceFroggy/sBot#7]
https://hostr.co/file/970/NSlWUXDfZGr1/sbotnewnew.png

https://hostr.co/file/970/n6NBlfpo3v00/newsBot.png

**Comment by randylicata** [comment]
My suggestion though since you are selling this now is to make it clear when it's running/when it worked. The controls and UI were pretty confusing last time but it was free so no biggie. Let me know if I can help. Good luck/Thanks!

**Comment by PrinceFroggy** [comment]
I'll let you have a free version! Also I made it crystal clear this time what is happening, thanks for the suggestion!
